{
    "_Type": "Action.Type.ODataService.DraftEnabled.Discard",
    "Target": {
        "Service": "/RISKAPPS/Services/riskmanagementService.service",
        "EntitySet": "Mitigations",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/RISKAPPS/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Discarded"
        }
    },
    "OnFailure": "/RISKAPPS/Actions/UpdateEntityFailureMessage.action"
}